# Generated by Django 4.2 on 2023-05-05 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('num_personal', models.IntegerField(null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.pensum')),
            ],
        ),
    ]
