# Generated by Django 4.2 on 2023-05-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0002_initial'),
        ('cargas', '0002_modcarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modcarga',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_cargas', to='pensum.curso'),
        ),
        migrations.AlterField(
            model_name='modcarga',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.curso'),
        ),
    ]
