# Generated by Django 4.2 on 2023-05-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargas', '0002_initial'),
        ('users', '0001_initial'),
        ('pensum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaacademicadetalle',
            name='docenteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.docente'),
        ),
        migrations.AddField(
            model_name='cargaacademicadetalle',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.pensum'),
        ),
        migrations.AddField(
            model_name='carga',
            name='carreraId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.carrera'),
        ),
    ]
