# Generated by Django 4.2 on 2023-05-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiclo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCurso', models.CharField(max_length=10)),
                ('nombreCurso', models.CharField(max_length=60)),
                ('horasSemana', models.IntegerField(blank=True, null=True)),
                ('laboratorio', models.BooleanField(default=False)),
                ('codigo_lab', models.CharField(blank=True, max_length=10, null=True)),
                ('horas_lab_sem', models.IntegerField(blank=True, null=True)),
                ('valido_semestres', models.IntegerField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrado', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPensum', models.CharField(max_length=10)),
                ('inicio_vigencia', models.IntegerField(blank=True, null=True)),
                ('desc_proceso', models.TextField(null=True)),
                ('cant_ciclos', models.IntegerField(blank=True, null=True)),
                ('valor_ef', models.IntegerField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePlan', models.CharField(max_length=60)),
                ('matutina', models.BooleanField(default=False)),
                ('verpertina', models.BooleanField(default=False)),
                ('nocturna', models.BooleanField(default=False)),
                ('sabados', models.BooleanField(default=False)),
                ('domingos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('registro_personal', models.IntegerField(blank=True, null=True)),
                ('dpi', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCarrera', models.CharField(max_length=10)),
                ('nombreCarrera', models.CharField(max_length=60)),
                ('duracionPeriodos', models.IntegerField(blank=True, null=True)),
                ('clasificacion', models.CharField(max_length=20, null=True)),
                ('partida', models.CharField(max_length=20, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('encargado_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.profesor')),
                ('tipo_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.cicloacademico')),
            ],
        ),
    ]
