# Generated by Django 4.2 on 2023-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradoAcademico',
        ),
        migrations.DeleteModel(
            name='Pensum',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='encargado_area',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='tipo_ciclo',
        ),
        migrations.AddField(
            model_name='curso',
            name='carrera',
            field=models.ManyToManyField(blank=True, null=True, to='pensum.carrera'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='idCarrera',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombreCarrera',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idCurso',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombreCurso',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.DeleteModel(
            name='CicloAcademico',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
