# Generated by Django 4.2 on 2023-05-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0002_delete_gradoacademico_delete_pensum_delete_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ciclo', models.CharField(choices=[('Semestral', 'Semestral'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual')], default='Semestral', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='tipo_ciclo',
            field=models.ForeignKey(default='Semestral', on_delete=django.db.models.deletion.CASCADE, to='pensum.ciclo'),
        ),
    ]
