# Generated by Django 4.2 on 2023-05-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0004_alter_carrera_tipo_ciclo_delete_ciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiclo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carrera',
            name='tipo_ciclo',
            field=models.ForeignKey(default='Semestral', on_delete=django.db.models.deletion.CASCADE, to='pensum.ciclo'),
        ),
    ]
