# Generated by Django 4.2 on 2023-05-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0005_ciclo_alter_carrera_tipo_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.ciclo'),
        ),
    ]
