# Generated by Django 4.2 on 2023-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0006_alter_carrera_tipo_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo_ciclo',
            field=models.CharField(blank=True, choices=[('Semestral', 'Semestral'), ('Anual', 'Anual'), ('Trimestral', 'Trimestral')], default='Semestral', max_length=50, null=True),
        ),
    ]
